#!/bin/bash

year=$1
day=$2

curl "https://adventofcode.com/$year/day/$day/input" \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: en' \
  -H 'cache-control: max-age=0' \
  -H 'cookie: _ga=GA1.2.691785033.1731712008; session=53616c7465645f5f4570d604a28271b5b2e85b68a6f42257fc4062fc2b9a4fe7e73ab7deeb49f9b1cd66172461b038d83370c5ad5934bb3ddb771da5c7b436d3; _gid=GA1.2.220945816.1733070122; _gat=1; _ga_MHSNPJKWC7=GS1.2.1733179027.7.1.1733187552.0.0.0' \
  -H 'dnt: 1' \
  -H 'priority: u=0, i' \
  -H 'referer: https://adventofcode.com/2024/day/1' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -o "./input/${year}_${day}.txt"
